Apply awaitility matchers for other instance messages MODINVSTOR-1001
folio-org/mod-inventory-storage pull request #863
Opened 2022-12-02 17:42 UTC by marcjohnson-kint

Follow on from #862 

Applies a similar approach to previous changes by using Hamcrest matchers directly with awaitility to avoid catching assertion errors or relying on ordering of messages.

The checks for multiple created messages uses a check for the expected number of messages and a loop instead of a combined matcher because the use of the combined matcher was unstable on Jenkins, yet stable locally.

2022-12-05 14:06 UTC, marcjohnson-kint commented on src/test/java/org/folio/rest/support/messages/InstanceEventMessageChecks.java
> +    await().during(1, SECONDS)
As I understand it, this uses the `await` method from the domain event assertions class that already defines an `atMost`. Does that not apply?

2022-12-07 12:31 UTC, marcjohnson-kint commented on src/test/java/org/folio/rest/support/messages/InstanceEventMessageChecks.java
> +    await().during(1, SECONDS)
It is not intended. Whilst I think this is unlikely to occur in practice, I agree with you that it should not be permissible in these tests.

I've changed the code to include an `at most` constraint that matches the `during` constraint.

2022-12-07 12:51 UTC, marcjohnson-kint commented on src/test/java/org/folio/rest/support/messages/InstanceEventMessageChecks.java
> +    await().during(1, SECONDS)
Hmm, it seems that introducing the `at most` with the same duration as `during` has made the tests unstable.

I've moved this PR to draft until that is resolved.

2022-12-07 12:55 UTC, marcjohnson-kint commented on src/test/java/org/folio/rest/support/messages/InstanceEventMessageChecks.java
> +    await().during(1, SECONDS)
It seems using the same value for both is a known failure situation - https://stackoverflow.com/questions/62830176/unpredictable-behavior-around-during-and-atmost-of-awaitility

2022-12-07 14:31 UTC, wwelling requested changes
LGTM

2022-12-07 14:45 UTC, marcjohnson-kint commented
> Rewrite code to be testable without race conditions.

What code are you suggesting should be rewrittten?

2022-12-07 15:02 UTC, wwelling commented
> > Rewrite code to be testable without race conditions.
> 
> What code are you suggesting should be rewrittten?

That I do not know, as no convention is in place to easily map between test and code being tested.

2022-12-08 12:24 UTC, merged