MODINVSTOR-1069: Added SuDoc call number implementation
folio-org/mod-inventory-storage pull request #914
Opened 2023-07-11 06:38 UTC by hasanepam

2023-07-11 11:08 UTC, mukhiddin-yusuf approved these changes

2023-07-19 10:15 UTC, hasanepam commented on src/test/java/org/folio/services/CallNumberUtilsTest.java
> +    "EP 1.23:91-44,D 3.186/7-3,EP 1.23:A 62 A 1.35,D 13 !3186 17 13 EP 11 223  !A 262  !A 11 235 EP 11 223 291 244"
Got it, let me change it as you are not the first person who told this), but thank you!

2023-07-19 14:22 UTC, hasanepam commented on src/main/java/org/folio/services/SuDocCallNumber.java
> +  public static final String STEM_PATTERN = "^([A-Za-z]+\\s*)(\\d+)(\\.[A-Za-z]*\\d*)(/*[A-Za-z]*\\d*-*\\d*)";
Replaced

2023-07-24 10:50 UTC, viacheslavkol requested changes

2023-07-24 13:01 UTC, hasanepam commented on src/main/java/org/folio/services/CallNumberUtils.java
>        .map(String::trim);
done!

2023-07-24 13:02 UTC, hasanepam commented on src/main/java/org/folio/rest/support/EffectiveCallNumberComponentsUtil.java
> +          item.getItemLevelCallNumberTypeId(),
Understood, done!

2023-07-24 16:13 UTC, viacheslavkol approved these changes

2023-07-24 17:46 UTC, merged