feat(MODINVSTOR-1133): add Library code, Location id, material type
folio-org/mod-inventory-storage pull request #949
Opened 2023-11-06 21:43 UTC by Roman-Leshchenko

…d to hierarchy response

### Purpose
_Describe the purpose of this pull request. Why is this change necessary? What problem does it solve?_

### Approach
_How does this change fulfill the purpose? Provide a high-level overview of the technical approach taken to address the problem._

### Changes Checklist
- [ ] **API Changes**: List any API paths, methods, request or response bodies changed, added, or removed.
- [ ] **Database Schema Changes**: Specify any database schema changes and their impact.
- [ ] **Interface Version Changes**: Indicate any changes to interface versions.
- [ ] **Interface Dependencies**: Note added or removed dependencies.
- [ ] **Permissions**: Document any changes to permissions.
- [ ] **Logging**: Confirm that logging is appropriately handled.
- [ ] **NEWS**: Ensure that the `NEWS` file is updated with relevant information about the changes made in this pull request.

### Related Issues
_List any Jira issues related to this pull request._

### Learning and Resources (if applicable)
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._

### Screenshots (if applicable)
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._

2023-11-16 12:02 UTC, psmagin commented
As this PR is not for merge and not ready for review I've converted it to draft.

2024-02-14 08:41 UTC, psmagin requested changes
Please update NEWS file

2024-02-19 09:18 UTC, psmagin approved these changes

2024-02-19 12:46 UTC, mukhiddin-yusuf approved these changes

2024-02-19 14:47 UTC, merged