feature(identifier-type): Add Cancelled LCCN type
folio-org/mod-inventory-storage pull request #973
Opened 2024-02-07 15:49 UTC by TsaghikKhachatryan

### Purpose
Add new new Identifier type: Cancelled LCCN

### Approach
Created a script to add new identifier type:

### Changes Checklist
- [ ] **API Changes**: Document any API paths, methods, request or response bodies changed, added, or removed.
- [ ] **Database Schema Changes**: Indicate any database schema changes and their impact. Confirm that migration scripts were created.
- [ ] **Interface Version Changes**: Indicate any changes to interface versions.
- [ ] **Interface Dependencies**: Document added or removed dependencies.
- [ ] **Permissions**: Document any changes to permissions.
- [ ] **Logging**: Confirm that logging is appropriately handled.
- [ ] **Unit Testing**: Confirm that changed classes were covered by unit tests.
- [ ] **Integration Testing**: Confirm that changed logic was covered by integration tests.
- [ ] **Manual Testing**: Confirm that changes were tested on local or dev environment.
- [ ] **NEWS**: Confirm that the NEWS file is updated with relevant information about the changes made in this pull request.

### Learning and Resources (if applicable)
https://folio-org.atlassian.net/browse/MODINVSTOR-1156

2024-02-07 16:48 UTC, viacheslavkol requested changes

2024-02-07 16:48 UTC, viacheslavkol commented on src/main/resources/templates/db_scripts/schema.json
> +      "fromModuleVersion": "26.1.0"
Should be 27.1.0

2024-02-07 16:48 UTC, viacheslavkol commented
Shouldn't be there some tests?

2024-02-07 21:14 UTC, TsaghikKhachatryan commented
> Shouldn't be there some tests?

added

2024-02-09 10:14 UTC, psmagin approved these changes

2024-02-10 19:00 UTC, GeloPakDev1 approved these changes

2024-02-14 17:15 UTC, merged